version: 2

#
# This file attempts to replicate:
#   docker run --restart=unless-stopped --env="constraint:node==web01" -d -p 5000:80 -e WEB_VOTE_NUMBER='01' --name web01 --net mynet --hostname votingapp.local web-vote-app
#   docker run --restart=unless-stopped --env="constraint:node==web01" -p 6379:6379 --name redis01 --net mynet -d redis  ## expose 6379 for debugging only!
#

services:
  web01:
    image: web-vote-app
    networks:
      - mynet
    ports:
      - "5000:80"
    environment:
      - WEB_VOTE_NUMBER="01"
    hostname: votingapp.local
  redis01:
    image: redis
    networks:
      - mynet
    ports:
      - "6379:6379"

#
# Is this necessary?  Ask someone from compose...
# 
networks:
  mynet:
    # Use the overlay driver for multi-host communication
    driver: overlay

